[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "clicktool"
version = "0.1"
description = "Common functions for @click"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
dependencies = [
    "click",
]
requires-python = ">=3.11"

[project.license]
text = "ISC"

[project.urls]
Homepage = "https://github.com/jakeogh/clicktool"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
clicktool = [
    "py.typed",
]
